### ISSUE TITLE
Code templates usage normalization

### ISSUE THREAD

**Issue by jcheron** [phpMv/php-vuejs#4]
### Problem
Do not use a path for each template, this path must be globally defined, and possibly changed (depending on the VueJS version used):
https://github.com/phpMv/php-vuejs/blob/ace6632407bb976948800d332dedd4f9e36a5bc1/src/PHPMV/parts/VueComputeds.php#L18
### Solution
Create a **VueJsLibrary** class similar to React's one, and define the template folder (base template + sub folder rev)
see https://github.com/phpMv/php-reactjs/blob/main/src/PHPMV/core/ReactLibrary.php

## Template parsing
Standardization between the 2 projects (php-reactjs and php-vuejs):
### template names 
- extension **tpl.js** (tpl to indicate that it is a template, js if it is a javascript file (which allows to have syntax highlighting in the IDE))
### variables replacement identification
- To identify the replacement variables : you need a beginning and an end tag: for the moment I use the comment `/*variableName*/`.

### Template parser usage
There is already a class dedicated to templates in **php-ui-common**, easy to use:
see https://github.com/phpMv/php-ui-common/blob/main/src/PHPMV/core/TemplateParser.php

#### Usage ####
```php
$this->renderTemplate = new TemplateParser();
//load the template file
$this->renderTemplate->loadTemplatefile(ReactLibrary::getTemplateFolder() . '/renderComponent');
//parse the template with some variables
$result=$this->renderTemplate->parse([
				'selector' => $selector,
				'component' => $component
			]);
```
The associated template file:

https://github.com/phpMv/php-reactjs/blob/5c49fb8a5c714175a19dedd9ebdb405d3f181121/src/PHPMV/core/templates/rev1/renderComponent.tpl.js#L1-L2

see https://github.com/phpMv/php-reactjs/blob/main/src/PHPMV/react/ReactJS.php for an example

**Comment by jguillaumesio** [comment]
This commit is a start of an answer, to this problem, let me know if there is something wrong with it
[https://github.com/phpMv/php-vuejs/tree/35b46267e4d6c40f838e5c4041a4b56489534fe4](https://github.com/phpMv/php-vuejs/tree/35b46267e4d6c40f838e5c4041a4b56489534fe4)

**Comment by jcheron** [comment]
Yes see https://github.com/phpMv/php-vuejs/issues/6
Templates can be used for specific structures...
but for the VueJS object, it's just a Javascript object, so it's easier to generate from a PHP array.
In java, it is built this way.
