### ISSUE TITLE
Hooks conception problem

### ISSUE THREAD

**Issue by jcheron** [phpMv/php-vuejs#7]
### VueHooks
The **VueHooks** class is useless.
With java, it doesn't exist and the Hooks are stored in a Map, so they should probably be in an associative array in PHP.

### Code repetitions
A lot of code repetition with the event adding methods, it should be factorized, since only the name of the event changes:
```php
	public function onMounted(string $body) {
	    $vh=new VueHook($body);
		$this->addHook("mounted", body);
		$this->script['mounted']=$vh->__toString();
	}
```

**Comment by jguillaumesio** [comment]
https://github.com/phpMv/php-vuejs/tree/ff452736127e6df4d34981998265faad9b7acc2f

Modified in this commit, hooks are now stored in an associative array with their name as index, hooks class deleted
