### ISSUE TITLE
Vue parts existence

### ISSUE THREAD

**Issue by jcheron** [phpMv/php-vuejs#8]
PHP is not Java, and it is not always advisable to have a strictly equivalent design between the 2 languages.
To illustrate this:

- The **VueData** class is nothing more than an associative array, object version (it inherits from ViewPart without doing anything more).

The **addData** method (and the other add...) is strange:

```php
	public function addData(string $name,string $value):void {
	    $this->data->put($name,$value);
	    $this->script['data']=$this->data->__toString();
	}
```

1. We add a key in **data** (ViewData)
2. and we add a key in **script**, which makes the toString of the data

We have the impression that **ViewData** is useless, and that we are doing duplicate things (in data and in script).

Why not make things simpler, without being influenced by java:
```php
	public function __construct() {
	    $this->data= [];
            ...
        }
	public function addData(string $name,$value):void {
	    $this->data[$name]=$value;
	}

	public function addDataRaw(string $name,string $value):void {
		$this->data[$name]="!!%$value%!!";//value must remain value
	}
```

**Comment by jguillaumesio** [comment]
I used to think of a new way for data, actually looking like this
https://github.com/phpMv/php-vuejs/tree/d4b570c6d559d69451ca6dccdd1997d1f981b11a
But I don't think that declaring data=>{} in the script array at the instantiation of the vue is a great thing, if someone has any idea on a better way tell me.
My idea would be not to have data in script if the array of data is empty, I could do it by merging data array like hooks, but data needs to be just after configuration things (el,vuetify,etc), so I could splice the script array to insert data just after configuration but I find it a bit hazardous.

**Comment by jcheron** [comment]
`$this->script` does not need to exist, let alone be initialized.
Just create it when you want to generate it, from `$this->data`, `$this->methods` and others.

**Comment by jguillaumesio** [comment]
I thought of this when I modified the way data are passed 
cf : https://github.com/phpMv/php-vuejs/commit/8be408a8b6a9dcd7af0d03835e18dda182a1bdf5

So it's done for this commit,
https://github.com/phpMv/php-vuejs/commit/ba0f301aefab681cbecc63ba4280e440ced68397

Thank you for the idea !

**Comment by jguillaumesio** [comment]
VuePart don't exist anymore since this commit
cf : https://github.com/phpMv/php-vuejs/commit/06f99d23f223cde0be253111af1dc6b145491d9c

Not having VueParts makes the code a lot more clear when reading it, thinking of it afterward, these classes were a useless add of complexity in the code.
